### PR TITLE
Case sensitivity in appmanifest_*.acf

### PR DESCRIPTION
**Pull request by mavit**
Key `appid` sometimes appears as `appID`.  Find that too.

### CODE REVIEW

**Comment by gasinvein** [comment]
Looks like this needs a rebase.

**Comment by gasinvein** [comment]
I'd really want to avoid external dependencies as much as possible, especially ones not widely available in distro package repositories.
But this is still a good catch. Can we implement this without involving 3rd-party module?

**Comment by mavit** [comment]
We could simply check for the two different keys `appid` and `appID`.  It feels like cheating, but itʼd probably work fine.

**Comment by gasinvein** [comment]
protontricks just constructs a new dict with all keys in lower case, and then lookups on it. Maybe we should do the same? Something like this:
```python
{k.lower(): v for k, v in app_mainfest['AppState'].items()}
```

**Pull request closed without merging**
